//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTaskWPF.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeightList
    {
        public int Id { get; set; }
        public Nullable<int> NumCar { get; set; }
        public Nullable<double> WNetto { get; set; }
        public Nullable<double> WBrutto { get; set; }
        public Nullable<double> WTara { get; set; }
        public Nullable<System.DateTime> DTTara { get; set; }
        public Nullable<System.DateTime> DTBrutto { get; set; }
        public int Car_Id { get; set; }
    
        public virtual Car Car { get; set; }
    }
}
